
language: cpp


# Build matrix
matrix:
  include:

    # Test with G++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # Test with G++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"



before_install:
  - eval "${MATRIX_EVAL}"
  - hostname
  - cd local_software
  - source env_vars.sh
  - ./setup_local_software.sh


install:
