
language: cpp

dist: trusty

# Build matrix
matrix:
  include:

    # Test with G++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=gfortran-7 && F90=gfortran-7"

    # Test with G++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gfortran-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && FC=gfortran-8 && F90=gfortran-8"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
     - libopenmpi-dev
      - numactl
      - cmake


before_install:
  - echo "${MATRIX_EVAL}"
  - eval "${MATRIX_EVAL}"
  - hostname
  - cd local_software || exit 1
  - source env_vars.sh || exit 1
  - ./setup_local_software.sh || exit 1


# Skip installation phase (install: true)
install: true
  - echo "Dummy installer"
