#
# Script for Travis CI
#
# See doc/travis_ci.txt for more information
#

language: cpp

dist: trusty

#
# We want to setup the 3rd party libraries and test SWEET
# with different software consellations
#
# This is called a build matrix and further described here
#
matrix:
  include:

    # Test with G++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7 && export FC=gfortran-7 && export F90=gfortran-7"

    # Test with G++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gfortran-8
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8 && export FC=gfortran-8 && export F90=gfortran-8"


#
# 3rd party libraries which should be downloaded from the ubuntu repository
#
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
     - libopenmpi-dev
      - numactl
      - cmake


before_install:
  # Load matrix environment
  - echo "${MATRIX_EVAL}"
  - eval "${MATRIX_EVAL}"

  # Debug output
  - hostname

  # Load SEET environment variables
  - cd local_software || exit 1
  - source env_vars.sh || exit 1

  # Setup additional SWEET software packages
  - ./setup_local_software.sh || exit 1


# Skip installation phase (install: true)
install: true
  - echo "Dummy installer"



# Cache installed software
# Once cached, the install scripts aren't executed anymore
cache:
  directories:
    # Cache the install directory for SWEET's 3rd party software
    local_software/local
