
language: cpp

dist: trusty

addons:
  apt:
    packages:
      - libopenmpi-dev
      - numactl
      - cmake

# Build matrix
matrix:
  include:

    # Test with G++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # Test with G++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"



before_install:
  - echo "${MATRIX_EVAL}"
  - eval "${MATRIX_EVAL}"
  - hostname
  - cd local_software || exit 1
  - source env_vars.sh || exit 1
  - ./setup_local_software.sh || exit 1


install:
  - echo "Dummy installer"
